### ISSUE TITLE
RTOS2: msgqueueu error with IAR 7.8 for cortex-m0 targets

### ISSUE THREAD

**Issue by 0xc0170** [ARM-software/CMSIS_5#164]
The code file msgqueue uses __CLZ: https://github.com/ARM-software/CMSIS_5/blob/develop/CMSIS/RTOS2/RTX/Source/rtx_msgqueue.c#L258

Code snippet:

```
  if ((__CLZ(msg_count) + __CLZ(block_size)) < 32) {
    EvrRtxMessageQueueError(NULL, osErrorParameter);
    return NULL;
}
```

This fails to build with IRA 7.8, for any cortex-m0 device, the error: ``Error[Pe020]: identifier "__cmsis_iar_clz" is undefined`` . I could not locate where ``__cmsis_iar_clz`` is defined .

From ``cmsis_iar`` header file, this is redefinition of ``__CZL``:

```
#if (__CORE__ == __ARM6M__)
  /* Avoid clash between intrinsics.h and arm_math.h when compiling for Cortex-M0. */
  #define __CLZ __cmsis_iar_clz
  #define __SSAT __cmsis_iar_ssat
#endif
```

I searched for ``__cmsis_iar_clz`` in IAR library sources, no luck. Where is this function declared and defined ?

Has anyone being able to build RTOS2 with IAR 7.8 or around ?

**Comment by ReinhardKeil** [comment]
We will replace CLZ on Cortex-M0/M0+/M23 with an alternative code.

**Comment by 0xc0170** [comment]
bump for the update

**Comment by c1728p9** [comment]
As a workaround the implementation in arm_math.h can be used. I created a PR for this in mbed-os here https://github.com/ARMmbed/mbed-os/pull/4198.

**Comment by JonatanAntoni** [comment]
Hi @0xc0170,

this issue should be resolved. May I ask you to close this issue if you do not have any further concerns, please?

Cheers,
Jonatan

**Comment by JonatanAntoni** [comment]
Closing this issue. Please feel free to reopen if you have further questions.
